#!/bin/bash
echo "- Internet status -"
echo "Settings:"
qmicli -d /dev/cdc-wdm0 --wds-get-current-settings
echo "Connection status:"
qmicli -d /dev/cdc-wdm0 --wds-get-packet-service-status
echo "Saved handler,cid:"
cat /tmp/qmihan
echo "Ping:"
ping -c 3 www.google.com
